server:
  port: 8080

spring:
  application:
    name: avalon-gateway
  zipkin: 
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
    traceId128: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - RequestTime=true
        
      routes: 
        - id: avalon-app
          uri: lb://AVALON-APP
          predicates:
            - Path=/app/**
          filters:
            # 熔断过滤器
            - name: Hystrix
              args:
                name: commonfallback
                fallbackUri: forward:/commonfallback
            - StripPrefix=1
        - id: avalon-account
          uri: lb://AVALON-ACCOUNT
          predicates: 
            - Path=/account/**
          filters:
            - StripPrefix=1
            
        - id: avalon-product
          uri: lb://AVALON-PRODUCT
          predicates: 
            - Path=/product/**
          filters:
            - StripPrefix=1
            
#熔断器配置
hystrix:
  command:
    execution: 
      isolation: 
        strategy: THREAD
        thread: 
          timeoutInMilliseconds: 3000
  shareSecurityContext: true
          
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
logging: 
  level: 
    root: info
    
