server:
  port: 8200
  

spring: 
  application: 
    name: avalon-app
  zipkin: 
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
    traceId128: true
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
feign:
  hystrix:
    enabled: true
