server:
  port: 8761
  

spring: 
  application: 
    name: avalon_register
  
eureka: 
  instance: 
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      
      
      
  