server:
  port: 8192
  

spring: 
  application: 
    name: avalon-product
  zipkin: 
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
    traceId128: true
    
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/